# Generated by Django 4.1.7 on 2024-08-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tankdata",
            name="last_updated",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
